import { HealthModule } from './health/health.module';
import { UserModule } from './user/user.module';
import { AuthModule } from './auth/auth.module';
import { DepartmentModule } from './department/department.module';
import { StatusModule } from './status/status.module';
import { SiteModule } from './site/site.module';
import { LeadModule } from './lead/lead.module';
import { LeadTagModule } from './lead-tag/lead-tag.module';
import { DashboardModule } from './dashboard/dashboard.module';
import { TaskModule } from './task/task.module';

export const modules = [HealthModule, UserModule, AuthModule, DepartmentModule, StatusModule, SiteModule, LeadModule, LeadTagModule, DashboardModule, TaskModule];
export { HealthModule } from './health/health.module';
export { UserModule } from './user/user.module';
export { AuthModule } from './auth/auth.module';
export { DepartmentModule } from './department/department.module';
export { StatusModule } from './status/status.module';
export { SiteModule } from './site/site.module';
export { LeadModule } from './lead/lead.module';
export { LeadTagModule } from './lead-tag/lead-tag.module';
export { DashboardModule } from './dashboard/dashboard.module';
export { TaskModule } from './task/task.module';